// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezevrmfsgdwlvufpyxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZXZybWZzZ2R3bHZ1ZnB5eHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjQ4NDMsImV4cCI6MjA2OTYwMDg0M30.6TgAD0U2LFGUcCELGTRGbwq0Aeib5E18H30bAnCbk0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});